### ISSUE TITLE
Undefined method

### ISSUE THREAD

**Issue by houdmont** [hearsayit/HearsayRequireJSBundle#68]
Call to undefined method `Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition::normalizeKeys()` in `DependencyInjection\Configuration.php` on line 54.

`->normalizeKeys(false)` was added to the configuration recently, however it causes the above exception to be thrown. (added [here](https://github.com/hearsayit/HearsayRequireJSBundle/commit/0cceff1c363566f7195ce93e757513a4b0ea50e3))

Which version of ArrayNodeDefinition supports `normalizeKeys` as I'm unable to find it?

**Comment by ihortymoshenko** [comment]
@houdmont, https://github.com/symfony/Config/blob/2.2/Definition/Builder/ArrayNodeDefinition.php#L310, since 2.2.

**Comment by houdmont** [comment]
Thank you,

Is it possible to state that fact in the dependencies?

The project I am currently working on is using v2.1 (which explains why I ended up with issues). I'm not sure if it's possible, but should composer.json state that symfony >= 2.2 is necessary?

**Comment by ihortymoshenko** [comment]
@houdmont, I'm not sure that's a good idea as I don't know how many people are using the old version.

**Comment by houdmont** [comment]
@IgorTimoshenko I can't understand why this would be a bad idea? 

If someone is using an old version of Symfony, adding this requirement would prevent them from breaking projects when including the RequireJSBundle.

If someone is using an older version of the RequireJSBundle, then they won't be affected by the new dependency requirement added to the latest version of the bundle.

I'm probably misunderstanding something here though, so please explain if that's the case.

**Comment by ihortymoshenko** [comment]
@houdmont, yeah, you're right. I'll fix it.

**Comment by ihortymoshenko** [comment]
@houdmont, moreover, it makes sense to require `"symfony/framework-bundle": ">=2.2.0"`.

**Comment by houdmont** [comment]
@IgorTimoshenko that's great! Thanks for helping, sorry I wasn't able to submit a pull request myself with a fix.
